services:
  backend_app:
    container_name: backend_api
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PYTHON_VERSION: ${PYTHON_VERSION}
    ports:
      - "${EXTERNAL_BACKEND_PORT}:8000"
    volumes:
      - .:/app
    restart: unless-stopped
    depends_on:
      - postgres_db
    networks:
      - smart_factory_network

  postgres_db:
    container_name: postgres_db
    image: postgres:${POSTGRES_DB_VERSION}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${POSTGRES_DB_EXTERNAL_PORT}:5432"
    volumes:
      - postgres_smart_factory_data:/var/lib/postgresql/data
    networks:
      - smart_factory_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} && psql -U ${POSTGRES_USER} -d ${POSTGRES_DB} -c \"SELECT 1;\"'"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s


  influxdb:
    container_name: influxdb
    image: influxdb:2.7
    ports:
      - "${INFLUXDB_EXTERNAL_PORT}:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_USER}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_BUCKET}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_TOKEN}
    volumes:
      - influxdb_data:/var/lib/influxdb2
      - ./iot_agent:/app
    networks:
      - smart_factory_network
    restart: unless-stopped

  
  iot-simulator:
    build:
      context: ./iot_agent/
      dockerfile: Dockerfile.iot
    image: iot-simulator:latest
    container_name: iot-machine-simulator
    restart: unless-stopped
    
    environment:
    - API_BASE_URL=http://backend_app:8000
    - GENERATION_FREQUENCY=30
    - METRICS_DIR=/app/metrics_data
    - STATE_DIR=/app/machine_states
    - API_MACHINES_ENDPOINT=/api/machine/all
    - API_INFLUX_ENDPOINT=/api/influx/insert
    - HISTORY_DIR=/app/history
    - HISTORY_WINDOW_HOURS=24

    volumes:
      - ./iot_agent:/app
      - ./iot_agent/metrics_data:/app/metrics_data
      - ./iot_agent/machine_states:/app/machine_states
    
    networks:
      - smart_factory_network
    
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    
    healthcheck:
      test: ["CMD-SHELL", "python -c 'import os; exit(0 if os.path.exists(\"/app/metrics_data/latest_metrics.json\") else 1)'"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 30s

  
volumes:
  postgres_smart_factory_data:
  influxdb_data:

networks:
  smart_factory_network:
