services:
  backend_app:
    container_name: backend_api
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PYTHON_VERSION: ${PYTHON_VERSION}
    ports:
      - "${EXTERNAL_PORT}:8000"
    volumes:
      - .:/app
    restart: unless-stopped
    depends_on:
      - postgres_db
    networks:
      - smart_factory_network

  postgres_db:
    container_name: postgres_db
    image: postgres:${POSTGRES_DB_VERSION}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${POSTGRES_DB_EXTERNAL_PORT}:5432"
    volumes:
      - postgres_smart_factory_data:/var/lib/postgresql/data
    networks:
      - smart_factory_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} && psql -U ${POSTGRES_USER} -d ${POSTGRES_DB} -c \"SELECT 1;\"'"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s


  influxdb:
    container_name: sf_influxdb
    image: influxdb:2.7
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_USER}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_BUCKET}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_TOKEN}
    volumes:
      - influxdb_data:/var/lib/influxdb2
    networks:
      - smart_factory_network
    restart: unless-stopped

  
volumes:
  postgres_smart_factory_data:
  influxdb_data:

networks:
  smart_factory_network:
