"""Enable cascade delete for machine logs

Revision ID: 1105b4645d33
Revises: e027657bef1f
Create Date: 2025-11-11 17:55:01.532604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1105b4645d33'
down_revision: Union[str, Sequence[str], None] = 'e027657bef1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('machine_logs', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Log ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('machine_logs', 'machine_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Machine reference',
               existing_nullable=False)
    op.alter_column('machine_logs', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Log timestamp',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('machine_logs', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Machine state',
               existing_nullable=True)
    op.alter_column('machine_logs', 'notes',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Comments or system-generated remarks',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('machine_logs', 'notes',
               existing_type=sa.TEXT(),
               comment='Comments or system-generated remarks',
               existing_nullable=True)
    op.alter_column('machine_logs', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='Machine state',
               existing_nullable=True)
    op.alter_column('machine_logs', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Log timestamp',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('machine_logs', 'machine_id',
               existing_type=sa.INTEGER(),
               comment='Machine reference',
               existing_nullable=False)
    op.alter_column('machine_logs', 'id',
               existing_type=sa.INTEGER(),
               comment='Log ID',
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###
