"""Add new constraint to factories table to assign only one factory to each user

Revision ID: 4a7181cbc126
Revises: df874ebe090d
Create Date: 2025-11-06 18:14:03.969067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a7181cbc126'
down_revision: Union[str, Sequence[str], None] = 'df874ebe090d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_owner_factory', 'factories', ['owner_id'])
    op.create_unique_constraint(None, 'factories', ['owner_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'factories', type_='unique')
    op.drop_constraint('unique_owner_factory', 'factories', type_='unique')
    # ### end Alembic commands ###
