"""Create machines table

Revision ID: 84863eba8d52
Revises: 89e231de8dfc
Create Date: 2025-11-08 13:58:29.249770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84863eba8d52'
down_revision: Union[str, Sequence[str], None] = '89e231de8dfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('machines',
    sa.Column('id', sa.Integer(), nullable=False, comment='Machine ID'),
    sa.Column('factory_id', sa.Integer(), nullable=False, comment='Linked factory'),
    sa.Column('name', sa.String(length=150), nullable=False, comment='Unique machine name'),
    sa.Column('serial_number', sa.String(length=100), nullable=False, comment='Unique serial number'),
    sa.Column('status', sa.String(length=20), server_default='Idle', nullable=False, comment='Machine status'),
    sa.Column('last_maintenance_date', sa.Date(), nullable=True, comment='Last maintenance date'),
    sa.Column('description', sa.Text(), nullable=True, comment='Notes or details'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Last update timestamp'),
    sa.CheckConstraint("status IN ('Running', 'Idle', 'Maintenance', 'Stopped')", name='valid_machine_status'),
    sa.ForeignKeyConstraint(['factory_id'], ['factories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('name', name='unique_machine_name'),
    sa.UniqueConstraint('serial_number'),
    sa.UniqueConstraint('serial_number', name='unique_machine_serial')
    )
    op.create_index(op.f('ix_machines_id'), 'machines', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_machines_id'), table_name='machines')
    op.drop_table('machines')
    # ### end Alembic commands ###
