"""Create shifts table

Revision ID: 89e231de8dfc
Revises: 4a7181cbc126
Create Date: 2025-11-07 20:54:11.344600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89e231de8dfc'
down_revision: Union[str, Sequence[str], None] = '4a7181cbc126'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shifts',
    sa.Column('id', sa.Integer(), nullable=False, comment='Shift ID'),
    sa.Column('factory_id', sa.Integer(), nullable=False, comment='One shift per factory'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Shift name'),
    sa.Column('start_time', sa.Time(), nullable=False, comment='Shift start time'),
    sa.Column('end_time', sa.Time(), nullable=False, comment='Shift end time'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Created timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Updated timestamp'),
    sa.ForeignKeyConstraint(['factory_id'], ['factories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('factory_id'),
    sa.UniqueConstraint('factory_id', name='unique_factory_shift')
    )
    op.create_index(op.f('ix_shifts_id'), 'shifts', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shifts_id'), table_name='shifts')
    op.drop_table('shifts')
    # ### end Alembic commands ###
