"""Create factories table

Revision ID: df874ebe090d
Revises: f9e3d962650f
Create Date: 2025-11-06 16:35:48.603134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df874ebe090d'
down_revision: Union[str, Sequence[str], None] = 'f9e3d962650f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('factories',
    sa.Column('id', sa.Integer(), nullable=False, comment='Factory ID'),
    sa.Column('name', sa.String(length=150), nullable=False, comment='Factory name'),
    sa.Column('location', sa.String(length=255), nullable=False, comment='Factory location'),
    sa.Column('description', sa.Text(), nullable=True, comment='Factory description'),
    sa.Column('owner_id', sa.Integer(), nullable=False, comment='Factory owner (client)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Last update timestamp'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_factories_id'), 'factories', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_factories_id'), table_name='factories')
    op.drop_table('factories')
    # ### end Alembic commands ###
