"""Create machine_logs model

Revision ID: e027657bef1f
Revises: 84863eba8d52
Create Date: 2025-11-11 09:11:17.996031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e027657bef1f'
down_revision: Union[str, Sequence[str], None] = '84863eba8d52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('machine_logs',
    sa.Column('id', sa.Integer(), nullable=False, comment='Log ID'),
    sa.Column('machine_id', sa.Integer(), nullable=False, comment='Machine reference'),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Log timestamp'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='Machine state'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Comments or system-generated remarks'),
    sa.CheckConstraint("status IN ('Running', 'Idle', 'Maintenance', 'Stopped')", name='valid_log_status'),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_machine_logs_id'), 'machine_logs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_machine_logs_id'), table_name='machine_logs')
    op.drop_table('machine_logs')
    # ### end Alembic commands ###
