"""Recreate users table

Revision ID: f9e3d962650f
Revises: 
Create Date: 2025-11-04 20:47:58.759646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9e3d962650f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False, comment='Unique user ID'),
    sa.Column('full_name', sa.String(length=20), nullable=False, comment='User full name'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='User email'),
    sa.Column('password_hash', sa.Text(), nullable=False, comment='Hashed password'),
    sa.Column('role', sa.String(length=10), nullable=False, comment="Role type: 'admin' or 'client'"),
    sa.Column('phone_number', sa.String(length=20), nullable=False, comment='must be unique if provided'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='When account was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Last update time'),
    sa.CheckConstraint("role IN ('admin', 'client')", name='check_role'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
